# Generated by Django 5.1.2 on 2024-10-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("User", models.CharField(max_length=25, unique=True)),
                ("First_Name", models.CharField(blank=True, max_length=25)),
                ("Last_Name", models.CharField(blank=True, max_length=25)),
                ("Password", models.CharField(max_length=128)),
                ("Created_date", models.DateField()),
            ],
        ),
    ]
