# Generated by Django 5.1.2 on 2024-10-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="Created_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
